services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_rice
      - sys_time
    volume:
